### ISSUE TITLE
In org-mode, a sentence that ends with a latex symbol will be wrapped in \dot{}

### ISSUE THREAD

**Issue by lizhuohua** [tecosaur/LaTeX-auto-activating-snippets#21] opened 2021-08-25 14:08 UTC
For example, if I want to type two sentences:

```
This sentence ends with a latex fragment \(x\). This is another sentence.
```

However, when I type `.␣`, the "wrap in \dot{}" rule is activated.

The root cause is that `laas-org-mathp` function cannot precisely determine whether the point is within a math block. According to the document of `org-element-at-point`, it only finds the **closest** element around the point. So even if the point is outside the math block, `laas-org-mathp` still return `t`.

Can we simply disable the rule `.␣`? Since we have another rule `..␣` which does exactly the same thing.

**Comment by ymarco** [comment] 2021-08-25 14:17
Duplicate of #16. Please look search the repo and look the existing issues before opening a new one.

**Closed by ymarco** 2021-08-25 14:17 UTC

**Comment by lizhuohua** [comment] 2021-08-25 14:21
Sorry, did a quick search but didn't notice. But good to know.
