### ISSUE TITLE
Maximum two characters in exponent auto curly wrap

### ISSUE THREAD

**Issue by Exr0n** [tecosaur/LaTeX-auto-activating-snippets#9] opened 2021-03-08 03:14 UTC
# Expected Behavior

- `a^123` -> `a^{123`
- `a^123 ` -> `a^{123} `
- `a^-33x ` -> `a^{-33x} `

Should the power include non-numeric characters (ex. variable names, `;`)? That runs the risk of consuming too much, but I vote that the exponent should be considered incomplete until a whitespace character is typed.

# Current Behavior

- `a^123` -> `a^{12}3`
- `a^123 ` -> `a^{12}3 `
- `a^-33x ` -> `a^{-3}3x`

(tested in org-mode)

**Comment by tecosaur** [comment] 2021-03-08 03:37
Just tested, cannot reproduce, and I don't see a snipped here for `^`.

**Comment by ymarco** [comment] 2021-03-08 07:43
> Should the power include non-numeric characters (ex. variable names, ;)? That runs the risk of consuming too much, but I vote that the exponent should be considered incomplete until a whitespace character is typed.

Theortically I'm OK with having a variable to switch between these two behaviors. However, I don't think we can add the general-case of
a^{12}X => a^{12X}
without binding a snippet for each and every letter x, with a condition would check for sub/superscripts on each keypress. The easier way to do it is with another post-self-insert-hook, but that's beyond the bounds of aas and laas.

...Meanwhile I'm fine with expanding the 1-9 and ii/jj snippets to check script bounds more thoroughly, and would accept a PR.


> Just tested, cannot reproduce, and I don't see a snipped here for `^`.
laas-subscript-snippets is the snippet list in question.

**Comment by ymarco** [comment] 2022-09-30 02:42
Closing because of staleness, I'd still accept a PR for `a_{12}3` → `a_{123}`

**Closed by ymarco** 2022-09-30 02:42 UTC
